### ISSUE TITLE
web support

### ISSUE THREAD

**Issue by ycryptx** [matheuscastroweb/tiktok-clone#1]
Currently the web build is broken. 
`yarn web` results in this error:
`/.../tiktok-clone/node_modules/react-native/Libraries/Components/TextInput/TextInputState.js
Module not found: Can't resolve '../../Utilities/Platform' in '/.../tiktok-clone/node_modules/react-native/Libraries/Components/TextInput'`

Are there plans to fix this?

P.S.
Great work on this project!!

**Comment by matheuscastroweb** [comment]
Hello! This project was not treated for web version. Only Android and IOS. I will remove the yarn web script. Thanks for letting me know.
