### ISSUE TITLE
React native version mismatch

### ISSUE THREAD

**Issue by svsundar81** [matheuscastroweb/tiktok-clone#3]
Hello Sir, I am constantly  getting this error in-spite of multiple try in different emulator devices. Do you know how to fix it
![Tiktok error](https://user-images.githubusercontent.com/19711603/86517802-b4708200-bdf9-11ea-8a0c-54ba6d07a9c2.jpg)

**Comment by matheuscastroweb** [comment]
Which version of Expo is installed?

Type in the terminal: `expo --version`

**Comment by matheuscastroweb** [comment]
Closed due to inactivity. Any problem open again.
